name: app_control_gastos_personales
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.2.0
  get: ^4.7.2
  go_router: ^16.0.0
  http: ^1.4.0
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.5.3
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/logo.png  

flutter_native_splash:  
  color: "#FFFFFF"
  image: assets/logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center